// This file centralizes mapping objects to convert API data into our DB schema.

export const countryCodeMap: Record<string, string> = {
  'Afghanistan': 'AFG', 'Albania': 'ALB', 'Algeria': 'DZA', 'Andorra': 'AND', 'Angola': 'AGO',
  'Argentina': 'ARG', 'Armenia': 'ARM', 'Australia': 'AUS', 'Austria': 'AUT', 'Azerbaijan': 'AZE',
  'Bahrain': 'BHR', 'Bangladesh': 'BGD', 'Barbados': 'BRB', 'Belarus': 'BLR', 'Belgium': 'BEL',
  'Belize': 'BLZ', 'Benin': 'BEN', 'Bhutan': 'BTN', 'Bolivia': 'BOL', 'Bosnia and Herzegovina': 'BIH',
  'Botswana': 'BWA', 'Brazil': 'BRA', 'Brunei': 'BRN', 'Bulgaria': 'BGR', 'Burkina Faso': 'BFA',
  'Burundi': 'BDI', 'Cambodia': 'KHM', 'Cameroon': 'CMR', 'Canada': 'CAN', 'Cape Verde': 'CPV',
  'Central African Republic': 'CAF', 'Chad': 'TCD', 'Chile': 'CHL', 'China': 'CHN', 'Colombia': 'COL',
  'Comoros': 'COM', 'Congo': 'COG', 'Costa Rica': 'CRI', 'Croatia': 'HRV', 'Cuba': 'CUB',
  'Cyprus': 'CYP', 'Czech Republic': 'CZE', 'Denmark': 'DNK', 'Djibouti': 'DJI', 'Dominica': 'DMA',
  'Dominican Republic': 'DOM', 'Ecuador': 'ECU', 'Egypt': 'EGY', 'El Salvador': 'SLV', 'Equatorial Guinea': 'GNQ',
  'Eritrea': 'ERI', 'Estonia': 'EST', 'Ethiopia': 'ETH', 'Fiji': 'FJI', 'Finland': 'FIN',
  'France': 'FRA', 'Gabon': 'GAB', 'Gambia': 'GMB', 'Georgia': 'GEO', 'Germany': 'DEU',
  'Ghana': 'GHA', 'Greece': 'GRC', 'Grenada': 'GRD', 'Guatemala': 'GTM', 'Guinea': 'GIN',
  'Guinea-Bissau': 'GNB', 'Guyana': 'GUY', 'Haiti': 'HTI', 'Honduras': 'HND', 'Hungary': 'HUN',
  'Iceland': 'ISL', 'India': 'IND', 'Indonesia': 'IDN', 'Iran': 'IRN', 'Iraq': 'IRQ',
  'Ireland': 'IRL', 'Israel': 'ISR', 'Italy': 'ITA', 'Jamaica': 'JAM', 'Japan': 'JPN',
  'Jordan': 'JOR', 'Kazakhstan': 'KAZ', 'Kenya': 'KEN', 'Kiribati': 'KIR', 'Kuwait': 'KWT',
  'Kyrgyzstan': 'KGZ', 'Laos': 'LAO', 'Latvia': 'LVA', 'Lebanon': 'LBN', 'Lesotho': 'LSO',
  'Liberia': 'LBR', 'Libya': 'LBY', 'Liechtenstein': 'LIE', 'Lithuania': 'LTU', 'Luxembourg': 'LUX',
  'Macedonia': 'MKD', 'Madagascar': 'MDG', 'Malawi': 'MWI', 'Malaysia': 'MYS', 'Maldives': 'MDV',
  'Mali': 'MLI', 'Malta': 'MLT', 'Marshall Islands': 'MHL', 'Mauritania': 'MRT', 'Mauritius': 'MUS',
  'Mexico': 'MEX', 'Micronesia': 'FSM', 'Moldova': 'MDA', 'Monaco': 'MCO', 'Mongolia': 'MNG',
  'Montenegro': 'MNE', 'Morocco': 'MAR', 'Mozambique': 'MOZ', 'Myanmar': 'MMR', 'Namibia': 'NAM',
  'Nauru': 'NRU', 'Nepal': 'NPL', 'Netherlands': 'NLD', 'New Zealand': 'NZL', 'Nicaragua': 'NIC',
  'Niger': 'NER', 'Nigeria': 'NGA', 'North Korea': 'PRK', 'Norway': 'NOR', 'Oman': 'OMN',
  'Pakistan': 'PAK', 'Palau': 'PLW', 'Palestine': 'PSE', 'Panama': 'PAN', 'Papua New Guinea': 'PNG',
  'Paraguay': 'PRY', 'Peru': 'PER', 'Philippines': 'PHL', 'Poland': 'POL', 'Portugal': 'PRT',
  'Qatar': 'QAT', 'Romania': 'ROU', 'Russia': 'RUS', 'Rwanda': 'RWA', 'Saint Kitts and Nevis': 'KNA',
  'Saint Lucia': 'LCA', 'Saint Vincent and the Grenadines': 'VCT', 'Samoa': 'WSM', 'San Marino': 'SMR',
  'Sao Tome and Principe': 'STP', 'Saudi Arabia': 'SAU', 'Senegal': 'SEN', 'Serbia': 'SRB',
  'Seychelles': 'SYC', 'Sierra Leone': 'SLE', 'Singapore': 'SGP', 'Slovakia': 'SVK', 'Slovenia': 'SVN',
  'Solomon Islands': 'SLB', 'Somalia': 'SOM', 'South Africa': 'ZAF', 'South Korea': 'KOR',
  'South Sudan': 'SSD', 'Spain': 'ESP', 'Sri Lanka': 'LKA', 'Sudan': 'SDN', 'Suriname': 'SUR',
  'Swaziland': 'SWZ', 'Sweden': 'SWE', 'Switzerland': 'CHE', 'Syria': 'SYR', 'Taiwan': 'TWN',
  'Tajikistan': 'TJK', 'Tanzania': 'TZA', 'Thailand': 'THA', 'Timor-Leste': 'TLS', 'Togo': 'TGO',
  'Tonga': 'TON', 'Trinidad and Tobago': 'TTO', 'Tunisia': 'TUN', 'Turkey': 'TUR', 'Turkmenistan': 'TKM',
  'Tuvalu': 'TUV', 'Uganda': 'UGA', 'Ukraine': 'UKR', 'United Arab Emirates': 'ARE', 'United Kingdom': 'GBR',
  'United States': 'USA', 'Uruguay': 'URY', 'Uzbekistan': 'UZB', 'Vanuatu': 'VUT', 'Vatican City': 'VAT',
  'Venezuela': 'VEN', 'Vietnam': 'VNM', 'Yemen': 'YEM', 'Zambia': 'ZMB', 'Zimbabwe': 'ZWE',
  // Additional mappings for common variations
  'Slovak Republic': 'SVK',
  'Democratic Republic of the Congo': 'COD', 'Republic of the Congo': 'COG', 'Ivory Coast': 'CIV',
  'East Timor': 'TLS', 'Eswatini': 'SWZ'
};

export const nationalityToCountryCodeMap: Record<string, string> = {
  'Afghan': 'AFG', 'Albanian': 'ALB', 'Algerian': 'DZA', 'American': 'USA', 'Andorran': 'AND',
  'Angolan': 'AGO', 'Argentine': 'ARG', 'Argentinian': 'ARG', 'Armenian': 'ARM', 'Australian': 'AUS',
  'Austrian': 'AUT', 'Azerbaijani': 'AZE', 'Bahraini': 'BHR', 'Bangladeshi': 'BGD', 'Barbadian': 'BRB',
  'Belarusian': 'BLR', 'Belgian': 'BEL', 'Belizean': 'BLZ', 'Beninese': 'BEN', 'Bhutanese': 'BTN',
  'Bolivian': 'BOL', 'Bosnian': 'BIH', 'Botswanan': 'BWA', 'Brazilian': 'BRA', 'Bruneian': 'BRN',
  'Bulgarian': 'BGR', 'Burkinabe': 'BFA', 'Burundian': 'BDI', 'Cambodian': 'KHM', 'Cameroonian': 'CMR',
  'Canadian': 'CAN', 'Cape Verdean': 'CPV', 'Central African': 'CAF', 'Chadian': 'TCD', 'Chilean': 'CHL',
  'Chinese': 'CHN', 'Colombian': 'COL', 'Comoran': 'COM', 'Congolese': 'COG', 'Costa Rican': 'CRI',
  'Croatian': 'HRV', 'Cuban': 'CUB', 'Cypriot': 'CYP', 'Czech': 'CZE', 'Danish': 'DNK',
  'Djiboutian': 'DJI', 'Dominican': 'DMA', 'Ecuadorian': 'ECU', 'Egyptian': 'EGY',
  'Salvadoran': 'SLV', 'Equatorial Guinean': 'GNQ', 'Eritrean': 'ERI', 'Estonian': 'EST', 'Ethiopian': 'ETH',
  'Fijian': 'FJI', 'Finnish': 'FIN', 'French': 'FRA', 'Gabonese': 'GAB', 'Gambian': 'GMB',
  'Georgian': 'GEO', 'German': 'DEU', 'Ghanaian': 'GHA', 'Greek': 'GRC', 'Grenadian': 'GRD',
  'Guatemalan': 'GTM', 'Guinean': 'GIN', 'Guinea-Bissauan': 'GNB', 'Guyanese': 'GUY', 'Haitian': 'HTI',
  'Honduran': 'HND', 'Hungarian': 'HUN', 'Icelandic': 'ISL', 'Indian': 'IND', 'Indonesian': 'IDN',
  'Iranian': 'IRN', 'Iraqi': 'IRQ', 'Irish': 'IRL', 'Israeli': 'ISR', 'Italian': 'ITA',
  'Jamaican': 'JAM', 'Japanese': 'JPN', 'Jordanian': 'JOR', 'Kazakhstani': 'KAZ', 'Kenyan': 'KEN',
  'Kiribati': 'KIR', 'Kuwaiti': 'KWT', 'Kyrgyzstani': 'KGZ', 'Laotian': 'LAO', 'Latvian': 'LVA',
  'Lebanese': 'LBN', 'Basotho': 'LSO', 'Liberian': 'LBR', 'Libyan': 'LBY', 'Liechtensteiner': 'LIE',
  'Lithuanian': 'LTU', 'Luxembourgish': 'LUX', 'Macedonian': 'MKD', 'Malagasy': 'MDG', 'Malawian': 'MWI',
  'Malaysian': 'MYS', 'Maldivian': 'MDV', 'Malian': 'MLI', 'Maltese': 'MLT', 'Marshallese': 'MHL',
  'Mauritanian': 'MRT', 'Mauritian': 'MUS', 'Mexican': 'MEX', 'Micronesian': 'FSM', 'Moldovan': 'MDA',
  'Monegasque': 'MCO', 'Mongolian': 'MNG', 'Montenegrin': 'MNE', 'Moroccan': 'MAR', 'Mozambican': 'MOZ',
  'Myanmar': 'MMR', 'Namibian': 'NAM', 'Nauruan': 'NRU', 'Nepalese': 'NPL', 'Dutch': 'NLD',
  'New Zealand': 'NZL', 'New Zealander': 'NZL', 'Nicaraguan': 'NIC', 'Nigerien': 'NER', 'Nigerian': 'NGA', 'North Korean': 'PRK',
  'Norwegian': 'NOR', 'Omani': 'OMN', 'Pakistani': 'PAK', 'Palauan': 'PLW', 'Palestinian': 'PSE',
  'Panamanian': 'PAN', 'Papua New Guinean': 'PNG', 'Paraguayan': 'PRY', 'Peruvian': 'PER', 'Filipino': 'PHL',
  'Polish': 'POL', 'Portuguese': 'PRT', 'Qatari': 'QAT', 'Romanian': 'ROU', 'Russian': 'RUS',
  'Rwandan': 'RWA', 'Kittitian': 'KNA', 'Saint Lucian': 'LCA', 'Vincentian': 'VCT', 'Samoan': 'WSM',
  'San Marinese': 'SMR', 'Sao Tomean': 'STP', 'Saudi Arabian': 'SAU', 'Senegalese': 'SEN', 'Serbian': 'SRB',
  'Seychellois': 'SYC', 'Sierra Leonean': 'SLE', 'Singaporean': 'SGP', 'Slovak': 'SVK', 'Slovenian': 'SVN',
  'Solomon Islander': 'SLB', 'Somali': 'SOM', 'South African': 'ZAF', 'South Korean': 'KOR',
  'South Sudanese': 'SSD', 'Spanish': 'ESP', 'Sri Lankan': 'LKA', 'Sudanese': 'SDN', 'Surinamese': 'SUR',
  'Swazi': 'SWZ', 'Swedish': 'SWE', 'Swiss': 'CHE', 'Syrian': 'SYR', 'Taiwanese': 'TWN',
  'Tajikistani': 'TJK', 'Tanzanian': 'TZA', 'Thai': 'THA', 'Timorese': 'TLS', 'Togolese': 'TGO',
  'Tongan': 'TON', 'Trinidadian': 'TTO', 'Tunisian': 'TUN', 'Turkish': 'TUR', 'Turkmen': 'TKM',
  'Tuvaluan': 'TUV', 'Ugandan': 'UGA', 'Ukrainian': 'UKR', 'Emirati': 'ARE', 'British': 'GBR',
  'Uruguayan': 'URY', 'Uzbekistani': 'UZB', 'Vanuatuan': 'VUT', 'Vatican': 'VAT',
  'Venezuelan': 'VEN', 'Vietnamese': 'VNM', 'Yemeni': 'YEM', 'Zambian': 'ZMB', 'Zimbabwean': 'ZWE',
  // Additional F1-specific nationalities
  'Monégasque': 'MCO',
  // Common variations and historical names
  'Yugoslav': 'SRB', 'Soviet': 'RUS', 'East German': 'DEU', 'West German': 'DEU',
  'Rhodesian': 'ZWE', 'Burmese': 'MMR', 'Ceylonese': 'LKA', 'Persian': 'IRN',
  'Holland': 'NLD', 'Hollander': 'NLD', 'Netherlandish': 'NLD'
};
